# Device Inventory (DI) Service Configuration
# CraftX.py FIDO Implementation

version: "1.0"
service:
  name: "CraftX-DI-Service"
  type: "device_inventory"

network:
  host: "0.0.0.0"
  port: 8445
  protocol: "https"

security:
  authentication:
    required: true
    methods:
      - "oauth2"
      - "client_cert"
      - "api_key"

  authorization:
    rbac_enabled: true
    roles:
      - "admin"
      - "operator"
      - "viewer"

inventory:
  database:
    type: "hybrid"
    local: "/var/lib/craftx/device_inventory.db"
    backup:
      enabled: true
      blockchain_anchor: true
      interval: "24h"

  device_tracking:
    lifecycle_states:
      - "manufactured"
      - "onboarded"
      - "active"
      - "maintenance"
      - "retired"

    attestation:
      frequency: "daily"
      storage: "ethereum"
      verification: true

blockchain:
  ethereum:
    network: "sepolia"
    contract: "0x50DB6330023d3Ee58906eCF3709419B25B1bcd53"
    rpc_url: "https://eth-anchor.craftx.elevatecraft.org"

  attestation:
    batch_size: 100
    confirmation_blocks: 3
    gas_optimization: true

api:
  endpoints:
    - "/api/v1/devices"
    - "/api/v1/inventory"
    - "/api/v1/attestations"
    - "/api/v1/lifecycle"

  rate_limiting:
    enabled: true
    requests_per_minute: 1000
    burst_size: 100

monitoring:
  metrics:
    enabled: true
    endpoint: "/metrics"

  alerts:
    device_offline: true
    attestation_failure: true
    security_events: true

compliance:
  fido_alliance: true
  data_retention: "7y"
  audit_logging: true
