# Device Onboarding (DO) Service Configuration
# CraftX.py FIDO Implementation

version: "1.0"
service:
  name: "CraftX-DO-Service"
  type: "device_onboarding"

network:
  host: "0.0.0.0"
  port: 8444
  protocol: "https"

security:
  tls:
    enabled: true
    cert_path: "/etc/ssl/certs/craftx-do.crt"
    key_path: "/etc/ssl/private/craftx-do.key"
    cipher_suites:
      - "TLS_AES_256_GCM_SHA384"
      - "TLS_CHACHA20_POLY1305_SHA256"

onboarding:
  max_devices: 10000
  session_timeout: "30m"
  retry_attempts: 3

voucher:
  verification:
    enabled: true
    algorithms:
      - "ES256"
      - "RS256"
  storage:
    type: "ethereum"
    contract: "0x50DB6330023d3Ee58906eCF3709419B25B1bcd53"

device_credentials:
  supported_types:
    - "x509"
    - "ieee802-1ar"
    - "tpm20"

  validation:
    certificate_chain: true
    crl_checking: true
    ocsp_checking: false

ethereum:
  network: "sepolia"
  rpc_url: "https://eth-anchor.craftx.elevatecraft.org"
  gas_limit: 150000
  confirmation_blocks: 1

logging:
  level: "info"
  onboarding_log: "/var/log/craftx/onboarding.log"
  security_events: "/var/log/craftx/security.log"
