[build]
  command = "cd netlify/functions && npm install"
  functions = "netlify/functions"
  publish = "."

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/auth/*"
  to = "/.netlify/functions/oauth-handler/:splat"
  status = 200

[[redirects]]
  from = "/callback/*"
  to = "/.netlify/functions/oauth-handler/:splat"
  status = 200

# WebAuthn endpoints
[[redirects]]
  from = "/webauthn/*"
  to = "/.netlify/functions/webauthn-handler/:splat"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://static.cloudflareinsights.com https://cdn.auth0.com https://appleid.cdn-apple.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://*.netlify.app https://*.googleapis.com https://api.github.com https://graph.microsoft.com https://appleid.apple.com https://orcid.org https://*.okta.com https://*.auth0.com; form-action 'self'; frame-ancestors 'none';"

# Cache static assets
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
